// <auto-generated />
using Estacionamento.api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estacionamento.api.Data.migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221110172544_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Estacionamento.api.Models.Veiculo", b =>
                {
                    b.Property<int>("VeiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataEntrada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSaida")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoraEntrada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoraSaida")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlacaDoCarro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoVeiculo")
                        .HasColumnType("INTEGER");

                    b.Property<double>("valorAPagar")
                        .HasColumnType("REAL");

                    b.HasKey("VeiculoId");

                    b.ToTable("Veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
